"""initial revision

Revision ID: ff5c116b6abd
Revises: 
Create Date: 2022-11-08 22:14:31.187568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5c116b6abd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('release_date', sa.Date(), nullable=True),
        sa.Column('image_url', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    op.create_table('artist',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nickname', sa.String(), nullable=True),
        sa.Column('link', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('release_date', sa.Date(), nullable=True),
        sa.Column('platform', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('image_url', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    op.create_table('link',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    op.create_table('album_artist',
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.Column('album_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
        sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
        sa.PrimaryKeyConstraint('artist_id', 'album_id')
    )
    op.create_table('album_featured',
        sa.Column('featured_id', sa.Integer(), nullable=False),
        sa.Column('album_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
        sa.ForeignKeyConstraint(['featured_id'], ['artist.id'], ),
        sa.PrimaryKeyConstraint('featured_id', 'album_id')
    )
    op.create_table('album_links',
        sa.Column('link_id', sa.Integer(), nullable=False),
        sa.Column('album_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
        sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
        sa.PrimaryKeyConstraint('link_id', 'album_id')
    )
    op.create_table('game_links',
        sa.Column('link_id', sa.Integer(), nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
        sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
        sa.PrimaryKeyConstraint('link_id', 'game_id')
    )
    op.create_table('track',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('album_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_artist',
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.Column('track_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
        sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
        sa.PrimaryKeyConstraint('artist_id', 'track_id')
    )
    op.create_table('track_featured',
        sa.Column('featured_id', sa.Integer(), nullable=False),
        sa.Column('track_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['featured_id'], ['artist.id'], ),
        sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
        sa.PrimaryKeyConstraint('featured_id', 'track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_featured')
    op.drop_table('track_artist')
    op.drop_table('track')
    op.drop_table('game_links')
    op.drop_table('album_links')
    op.drop_table('album_featured')
    op.drop_table('album_artist')
    op.drop_table('user')
    op.drop_table('link')
    op.drop_table('game')
    op.drop_table('artist')
    op.drop_table('album')
    # ### end Alembic commands ###
